nginx:
  restart: unless-stopped
  image: mobilizingcs/nginx
  links:
  - ohmage:ohmage
  - wiki:wiki
  ports:
  - "80:80"

ohmage:
  restart: unless-stopped
  image: ohmage/base
  links:
  - mysql:mysql

wiki:
  restart: unless-stopped
  image: mobilizingcs/wiki

mysql:
  restart: unless-stopped
  image: mysql:5.6.27
  environment:
  - MYSQL_ROOT_PASSWORD=setmebetter
