nginx:
  restart: unless-stopped
  image: mobilizingcs/nginx
  links:
  - ohmage:ohmage
  - wiki:wiki
  - ocpu:ocpu
  - rstudio:rstudio
  - pw:pw
  volumes_from:
    - ohmagex
  ports:
  - "80:80"

ohmage:
  restart: unless-stopped
  image: ohmage/base
  volumes:
  - .data/ohmage:/var/lib/mysql
  links:
  - mysql:mysql

wiki:
  restart: unless-stopped
  image: mobilizingcs/wiki

ocpu:
  restart: unless-stopped
  image: mobilizingcs/ocpu

rstudio:
  restart: unless-stopped
  image: mobilizingcs/rstudio

mysql:
  restart: unless-stopped
  image: mysql:5.6.27
  volumes:
  - .data/mysql:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=setmebetter

pw:
  restart: unless-stopped
  image: stevenolen/pw

ohmagex:
  image: mobilizingcs/ohmagex
  entrypoint: /bin/echo 'ohmagex compiled resources container'
