version: '2'
services:
  nginx:
    restart: unless-stopped
    environment:
      - FORCE_SSL=true
      - VIRTUAL_HOST=http://${MIAB_URL},https://${MIAB_URL}
      - EXCLUDE_PORTS=443
      - EXTRA_SETTINGS=acl fix_rstudio res.hdr(Location) -m sub rstudio:8787, rspirep ^Location:\ https://rstudio:8787/(.*)      Location:\ https://${MIAB_URL}/navbar/rstudio/\1 if fix_rstudio, acl fix_https res.hdr(Location) -m sub http://, rspirep ^Location:\ http://(.*)      Location:\ https://\1 if fix_https
    networks:
      - inside
      - outside
 
  ohmage:
    restart: unless-stopped
    networks:
      - inside
    environment:
      - MYSQL_PASSWORD=abetterpassword
 
  db:
    restart: unless-stopped
    networks:
      - inside
    environment:
      - MYSQL_PASSWORD=abetterpassword
      - MYSQL_ROOT_PASSWORD=abetterrootpassword
 
  ocpu:
    restart: unless-stopped
    networks:
      - inside
  
  rstudio:
    restart: unless-stopped
    networks:
      - inside
    environment:
      - MYSQL_PASSWORD=abetterpassword
  
  pw:
    restart: unless-stopped
    networks:
      - inside

  # a simple postfix container as a sample.
  # mail:
  #   image: alezzandro/postfix
  #   restart: unless-stopped
  #   environment:
  #     - myhostname=${MIAB_URL}
  #   networks:
  #     - inside

  # if you use mailgun, this is a great way to to integrate all outgoing messages!
  mail:
    image: ryangraham/postfix-mailgun
    restart: unless-stopped
    environment:
      - MG_USER=mailgun.smtpuser@yourdomain.com
      - MG_PASS=mailgunsmtppassword
    networks:
      - inside

networks:
  outside:
    external:
      # if you're using a load balancer as a reverse proxy, don't forget to comment out port 80 in docker-compose.yml
      name: lb_outside
  inside:
    driver: bridge
