nginx:
  restart: unless-stopped
  image: mobilizingcs/nginx
  links:
  - ohmage:ohmage
  - wiki:wiki
  - ocpu:ocpu
  - rstudio:rstudio
  - pw:pw
  volumes_from:
  - ohmagex
  - dashboard
  ports:
  - "80:80"

ohmage:
  restart: unless-stopped
  image: ohmage/base
  volumes:
  - .data/ohmage:/var/lib/ohmage
  links:
  - mysql:mysql

wiki:
  restart: unless-stopped
  image: mobilizingcs/wiki

ocpu:
  restart: unless-stopped
  image: mobilizingcs/ocpu

rstudio:
  restart: unless-stopped
  image: mobilizingcs/rstudio
  volumes:
  - .data/rstudio/home:/home
  links:
  - mysql:mysql
  environment:
  - SYNC=1

mysql:
  restart: unless-stopped
  image: mysql:5.6.27
  # comment out volumes if testing on osx. mysql/docker/osx permissions issue.
  volumes:
  - .data/mysql:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=setmebetter

pw:
  restart: unless-stopped
  image: stevenolen/pw

ohmagex:
  image: mobilizingcs/ohmagex
  entrypoint: /bin/echo 'ohmagex compiled resources container'

dashboard:
  image: mobilizingcs/dashboard
  entrypoint: /bin/echo 'dashboard compiled resources container'
